version: '3.8'

services:
  stats-server:
    build: ewm-stats-service/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: my_stats_user
      SPRING_DATASOURCE_PASSWORD: my_stats_password

  stats-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: my_stats_user
      POSTGRES_PASSWORD: my_stats_password

  ewm-service:
    build: main-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      MAIN_SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/main
      MAIN_SPRING_DATASOURCE_USERNAME: my_main_user
      MAIN_SPRING_DATASOURCE_PASSWORD: my_main_password

  ewm-db:
    image: postgres:15.3-alpine3.18
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: my_main_user
      POSTGRES_PASSWORD: my_main_password